##version: '3.8'

##services:
  ##web:
   ## build: ./Src
   ## container_name: unievents_web
   ## ports:
   ##   - "8080:80"
   ## volumes:
   ##   - ./Src:/var/www/html
   ## depends_on:
   ##   - db
    ##environment:
    ##  - MYSQL_HOST=db
    ##  - MYSQL_DATABASE=unievents
    ##  - MYSQL_USER=admin
    ##  - MYSQL_PASSWORD=admin123

 ## db:
  ##  image: mysql:8.0
  ##  container_name: unievents_db
  ##  restart: always
  ##  environment:
    ##  MYSQL_ROOT_PASSWORD: root123
    ##  MYSQL_DATABASE: unievents
    ##  MYSQL_USER: admin
    ##  MYSQL_PASSWORD: admin123
    ##ports:
    ##  - "3306:3306"
    ##volumes:
    ##  - mysqldata:/var/lib/mysql

##volumes:
 ## mysqldata:
