version: '3.8'

services:
  web:
    build: .
    container_name: unievents-app
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=unievents
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: unievents-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unievents
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
